name: Manual Trigger Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to'
        required: true
        default: 'Re-Run Action'
        type: choice
        options:
          - Re-Run Action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Set environment variables
      run: echo "NODE_ENV=production" >> $GITHUB_ENV

    - name: Add Node.js to PATH
      run: echo "/home/runner/work/test-repo" >> $GITHUB_PATH

    - name: Display directory structure
      run: ls -la /home/runner/work/test-repo/*

    #- name: Run a script
      #run: ./package.json
      #working-directory: /home/runner/work/test-repo

    #- name: Run a one-line script
      #run: echo "Deploying to ${{ github.event.inputs.environment }} environment"
